language: node_js
node_js:
  - "6"
scripts:
  - npm run seed-db
  - npm test
services: 
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start